### ISSUE TITLE
outdir

### ISSUE THREAD

**Issue by fabiencastan** [jaeandersson/swig#1]
I'm testing your work to get a matlab support in swig. That's a really useful thing! Thanks!

It seems that the "outdir" argument is not taken into account.

A fix has been done on another language for the same problem:
https://github.com/swig/swig/commit/138af71cfdea5020d96a3b10972d8a20353118d7

**Comment by jaeandersson** [comment]
OK, thanks! I will have a look at it.

**Comment by jaeandersson** [comment]
@fabiencostan Btw, feel free to fork the repo and make pull requests.

**Comment by jaeandersson** [comment]
I mean @fabiencastan

**Comment by ibell** [comment]
Looks like this issue can be closed as it is fixed in #8
