### ISSUE TITLE
MSVC chokes with warning "compiler limit : blocks nested too deeply"

### ISSUE THREAD

**Issue by ibell** [jaeandersson/swig#12]
Error message:

```
CoolPropMATLAB_wrap.cxx(14944): fatal error C1061: compiler limit : blocks nested too deeply [C:\Users\ian\slave\MATLAB-windows32\build\build\CoolPropMATLAB_wrap.vcxproj]
```

Cause:
In the conditional tree in `swigConstant()`, MSVC has a limit on the number of levels you can nest namespaces, which, here, means also the number of elseif branches.  As far as I can tell, the limit is 128 elseif branches.  A map (string->int) would fix this problem, but I gather we don't want to go that route.

Another solution is X macros and a switch, but I think you might have the same problem with being limited to 128 keys in the switch.  Or perhaps not...

**Comment by jaeandersson** [comment]
I think the best solution is to do the same as for the functions, to pass a number and use the string just for consistency checking. Here is an extract from my generated front-end to CasADi:

``` c++
  case 720: if ((name_ok=!strcmp("Sparsity_size1",cmd))) _wrap_Sparsity_size1(resc,resv,argc,(mxArray**)(argv)); break;
  case 721: if ((name_ok=!strcmp("Sparsity_size2",cmd))) _wrap_Sparsity_size2(resc,resv,argc,(mxArray**)(argv)); break;
  case 722: if ((name_ok=!strcmp("Sparsity_numel",cmd))) _wrap_Sparsity_numel(resc,resv,argc,(mxArray**)(argv)); break;
```

The same approach can be used for the constants. There is no reason why it wouldn't work.

I don't think MSVC will complain. If it does, it's very strange. I think large switches are common. Note that a switch will be translated to a lookup table in the compiled code. The compiler will jump straight to the correct case. So O(1) complexity with a small constant.  A map would require a binary search so O(log(N)) complexity, plus all the problems with keeping the map in memory and constructing it. Plus the fact that it won't work in C. The current design is equivalent to a linear search, so O(N) complexity.

So as I see it: a switch, definately.

**Comment by jaeandersson** [comment]
If you want, I can give it a shot.

**Comment by ibell** [comment]
_bump_

The SWIG MATLAB wrapper is VERY slow compared to old hand-built wrapper, and i suspect it is a result of all this string comparison.  String comparison should be avoided at all cost when it comes to speed.

**Comment by jaeandersson** [comment]
OK. I'll see what I can do. The fundamental problem is that there is currently a linear complexity in the number of constants for getting a single constant. If you want all constants, you get a quadratic complexity. Changing as proposed will give a constant complexity for a single element lookup and linear for all. The string comparison will just add a multiplicative factor, won't affect the complexity.

**Comment by jaeandersson** [comment]
i'm at it.

**Comment by jaeandersson** [comment]
@ibell - I've replaced the conditional tree with a switch. Could you check if it works better now?

**Comment by ibell** [comment]
I dunno if I have done something idiotic, but it seems the `swigConstant()` function still uses a linked string comparison tree?

**Comment by ibell** [comment]
Yup, I was pulling from the wrong repo, seems your fix works (at least compiles).

**Comment by jaeandersson** [comment]
Great! Is it also a lot faster?
