### ISSUE TITLE
Cannot pass reference to std::vector<double>

### ISSUE THREAD

**Issue by ibell** [jaeandersson/swig#16]
I try to pass `const &` to `std::vector<double>` to my function, and when I do so, I get the error:

```
Warning: asptr for seq 
Warning: in method 'AbstractState_set_mole_fractions', argument 2 of type
'std::vector< double,std::allocator< double > > const &' 
```

I don't see any examples that pass STL containers, and I wonder if this is just something that isn't implemented yet?  Actually I am passing a DoubleVector instance which is just a wrapper of a std::vector<double>

**Comment by jaeandersson** [comment]
Do you really want to work with `std::vector<double>` in MATLAB? Don't you want to work with MATLAB matrices?

**Comment by ibell** [comment]
I would be happy to work with MATLAB matrices as well, but I can't figure
out why I can't pass anything (matrix, DoubleVector, etc.) to my C++
function that takes a const std::vector<double> &.  Should this work?  I
always get the error shown above.

**Comment by jaeandersson** [comment]
I assume that you have instantiated the template:

```
%include "std_vector.i"
...
%template(DoubleVector)             std::vector<double>;
```

?

**Comment by jaeandersson** [comment]
Did you do `std::vector< double> const &` instead of `const std::vector< double> &`?

**Comment by ibell** [comment]
Yes to your question about the template instantiation!  I'm not sure I
understand the difference between the two const references you show, should
that have an impact on how it gets wrapped?  This works fine in the other
wrappers.

**Comment by jaeandersson** [comment]
About, `std::vector< double> const &`, I thought `const std::vector< double> &` would be more standard. I have a vague memory that the placement of const could influence SWIG's  pattern matching. Could be wrong though.

**Comment by ibell** [comment]
Yes I use the first one: const  std::vector< double> &

I am still stuck not being able to get anything to pass to the function

**Comment by ibell** [comment]
Here is a simple demonstration of the problem:

```
%module example

%include "exception.i"
%include stl.i

// Instantiate templates used by example
namespace std {
   %template(DoubleVector) vector<double>;
}

%inline %{
#include <vector>

double index(const std::vector<double> & v, int i){
    return v[i];
};
%}
```

which is compiled using

```
./swig -matlab -c++ example.i
g++ -shared -fPIC -o example_wrap.mexmaci64 example_wrap.cxx  -I/Applications/MATLAB_R2014a.app/extern/include/ -L/Applications/MATLAB_R2014a.app/bin/maci64 -lmex -lmx -lmat
```

and the script `runme.m` 

```
v = example.DoubleVector();
v.push_back(1.0);
v.push_back(2.0);
example.index(v,1);
```

yields the output

```
Warning: asptr for seq 
Warning: in method 'index', argument 1 of type 'std::vector<
double,std::allocator< double > > const &' 
Error using example_wrap
Failure in function index.

Error in example.index (line 2)
  [varargout{1:max(1,nargout)}] = example_wrap(42,'_wrap_index',varargin{:});

Error in runme (line 4)
example.index(v,1);
```

**Comment by jaeandersson** [comment]
Ah, ok. What happens if you do:

``` matlab
v = [1,0, 2.0]
example.index(v,1);
```

or

``` matlab
v = {1,0, 2.0}
example.index(v,1);
```

?

**Comment by ibell** [comment]
Nope, same failure. It seems the swig::asptr doesn't handle the cast to a
raw pointer properly with all these objects.

**Comment by jaeandersson** [comment]
OK. This is weird, I use `std::vector<double>` myself extensively. Unfortunately, I won't be able to have a look at it the next couple of weeks.

**Comment by ibell** [comment]
What revision? What OS? What MATLAB version?

**Comment by jaeandersson** [comment]
MATLAB 2014b, OS X & Linux. But I didn't check the above explicitly. Also, I don't have many free-standing functions like this, it's mostly classes. I can have a look at it later, but not now. Anyway, the example above is very well isolated, so should be straightforward.

**Comment by ibell** [comment]
_bump_  This is a blocking bug for me now, and I was hoping that you might have some time to take a look in the near future.

**Comment by jaeandersson** [comment]
Ok, I'm going to have a look at it as soon as the project I'm working on reaches the MATLAB stage. Still a few weeks into the future.

**Comment by ianhbell** [comment]
_BUMP_ - any chance of your taking a look?

**Comment by jaeandersson** [comment]
I'll have a look later this week, if it didn't get fixed already by #22. I need finish the refactoring of subsref, subsasgn first.

**Comment by ibell** [comment]
No problem, just want to make sure it doesn't get neglected, this is a
pretty serious problem for me.

**Comment by jaeandersson** [comment]
Anyway, if I were you I would write an in typemap from Matlab mxArray to const vector<double>&. It's a bit weird to work with std::vector<double> for a matlab user. Unless you're afraid of the extra copying operation.

**Comment by jaeandersson** [comment]
My ambition is to get the module merged with master, so this has to be fixed.
As for my own code, I decided to redefine all the typemaps, so I hardly use `stl.i` myself. I just instantiate the templates without creating proxy classes.

**Comment by ibell** [comment]
I'd be happy for matrices/arrays to work natively, that is obviously the
ideal solution.  The STL vector was a workaround.

**Comment by jaeandersson** [comment]
This should be working now, but there is plenty of work still to be done on std.i typemaps. I hardly use these typemaps myself (I redefine all typemaps I need), and I am not very familiar with how they work. So it would be great if someone else could take the lead on fixing the std.i typemaps.

**Comment by ibell** [comment]
Awesome! I'll give it a try tonight

**Comment by ibell** [comment]
Can you reopen this issue? I can't.

With this .i file:

```
%module example

%include "exception.i"
%include stl.i

// Instantiate templates used by example
namespace std {  %template(DoubleVector) vector<double>; }

%inline %{
#include <vector>
double index(const std::vector<double> & v, int i){ return v[i]; };
%}
```

I try to use this sample code:

```
v = [1.0,2.0];
example.index(v,1);
```

which yields the error:

```
Warning: in method 'index', argument 1 of type 'std::vector< double,std::allocator<
double > > const &' 
Error using example_wrap
Fatal error.

Error in example.index (line 2)
  [varargout{1:max(1,nargout)}] = example_wrap(69,varargin{:});

Error in runme (line 2)
example.index(v,1);
```

FYI, using the `DoubleVector` proxy class and a few `push_back()` does in fact work (thanks for making that work)

**Comment by ibell** [comment]
Would be fantastic if I could skip the proxy classes...

**Comment by jaeandersson** [comment]
This is a separate issue. You're missing the corresponding typemap from `mxArray` row vector to `const vector<double> &`.

e.g.

```
typemap(typecheck) const std::vector<double>& {
...
}

typemap(in) const std::vector<double>& (std::vector<double> tmp) {
...
}
```

I have opened #29 for this.
