### ISSUE TITLE
Speed is not too impressive

### ISSUE THREAD

**Issue by ibell** [jaeandersson/swig#18]
Unfortunately I don't have any benchmarks to share, but I have had several complaints from our users of the swig+MATLAB wrapper that the computational speed isn't very good,and much slower than our simpler C wrapper.  I suspect it has to do with all the lookup of the class methods using strings.  Is there any reason to use strings rather than something like auto-generated enumerations?  That should be much faster.

**Comment by jaeandersson** [comment]
Hmm, as far as I know, auto-generated enums are used everywhere (in latest versions). The strings are just for consistency checking and readability. They could be left out completely or be replaced with hashes. Can you provide more detail?

**Comment by ibell** [comment]
Let me put together a couple of mini benchmarks to see where we stand

**Comment by jaeandersson** [comment]
Also, keep in mind that costants are "persistent" variables. They will be read it on first use. For subsequent calls they are cached in MATLAB.

**Comment by jaeandersson** [comment]
Also, please confirm that the constant retrieval in the generated code is using a lookup (switch-statement) and not something like if-elseif-elseif -elseif-else.

**Comment by ibell** [comment]
Class instantiation:
In python:

```
import time, CoolProp
t1 = time.time()
for i in range(10000):
    AS = CoolProp.AbstractState('HEOS','Water')
t2 = time.time()
print t2-t1
```

takes 0.7 s, while in MATLAB, this

```
t1 = tic();
for i = 1:10000
    AS =  CoolProp.AbstractState.factory('HEOS','Water');
end
t2 = toc();
disp(t2-t1)
```

takes 5.833 s.  Aside from the wrapper code, the python and MATLAB wrappers are identical at the C++ level.

**Comment by ibell** [comment]
And calling a nearly trivial method (close to no overhead at the c++ level):

```
import time, CoolProp
t1 = time.time()
AS = CoolProp.AbstractState('HEOS','Water')
for i in range(100000):
    R = AS.gas_constant()
t2 = time.time()
print t2-t1
```

takes 0.0261 s in python, and in MATLAB, this

```
t1 = tic();
AS =  CoolProp.AbstractState.factory('HEOS','Water');
for i = 1:100000
    R = AS.gas_constant();
end
t2 = toc();
disp(t2-t1)
```

takes 14.7 s.

As my users have noted, this isn't too great.

**Comment by jaeandersson** [comment]
So gas_constant is a member function? Could it be that it is cached in Python? It could also just be the string comparisons. I guess you could fix all string comparisons at compile time by adding a macro such as `#define strcmp(x, y) 0` in the wrapper file. Could give a clue of what takes time.

**Comment by ibell** [comment]
Yes `gas_constant` is a member function of the `AbstractState` class.  Looking at the profile in MATLAB, it seems there is quite a lot of indirection.  I'll try the strcmp thing to see if that makes a difference.

**Comment by jaeandersson** [comment]
It could also be the creation of strings and the like. What is the return type of `gas_constant`? 
Should be said that the current timings are maybe slow compared to Python, but they are not really "slow". I mean, 0.14 ms and 0.6 ms in the above in the above code. That's certainly fast enough for my application.

**Comment by ibell** [comment]
140 us overhead per call is VERY slow for my application.  The function
call time at the C++ level is about 0.1 us/call, and 140 ms/call is
essentially 100% overhead.

**Comment by jaeandersson** [comment]
That's clear. Anyway, I'm sure we can get things go faster. Not sure we can reach anything close to Python speed though.

**Comment by jaeandersson** [comment]
I have refactored this code now and there are no temporary strings being created anymore, neither on the MATLAB side, nor on the MEX side. This should decrease overhead for function calls and constant lookup a lot. I don't see how it can decreased much further with the current design, so I'll close the issue. Feel free to reopen, but as I said, I don't see how to get much further with this.

I would expect at least an order of magnitude faster after these changes. Is that what you see? If not, the bottleneck is probably somewhere else.
