### ISSUE TITLE
Move setup script inside generated package

### ISSUE THREAD

**Issue by jaeandersson** [jaeandersson/swig#24]
@jgillis added a setup script in c67924ddfdbea5c3bc4a08a3f5bb49d302ebabea. I think it would be more prudent to move this script inside the +package directory.

**Comment by KrisThielemans** [comment]
yes, I agree. I also think that name needs to be configurable (sadly) to avoid conflicts with any known function

**Comment by jaeandersson** [comment]
@jgillis By default, the setup script will be empty (at least after latest refactoring). Can we convert the script to a MATLAB function (with no inputs or outputs) with the same name? Then we can have the script only created when it is actually non-empty and we can call `mexCallMATLABWithTrap` instead of `mexEvalString` and do better error handling and resolve the case when the script is not present.

**Comment by jaeandersson** [comment]
I tried removing the script alltogether, see f1a015516197cdc8c2e2cea484ee226ac526e919.

This required me to refactor CasADi as follows: https://github.com/casadi/casadi/commit/b0f4fc016e1f89edf08996b4b19df36808bd5ac3

In principle, I don't see a good reason to keep the setup scripts. If the user wants one, he can define his own (project-specific one) in the `%init` section.

@jgillis Please review these commits. I've not yet pushed them to develop/matlab.

**Comment by KrisThielemans** [comment]
I’m in favour of this removing this script. The setup script can lead to name clashes, and means another file to take care of with your build system.

**Comment by ibell** [comment]
+1 on removing the setup file if possible.  I get questions from my users about why the file is empty.

**Comment by jaeandersson** [comment]
OK, it has been removed now.

**Comment by jaeandersson** [comment]
@KrisThielemans @ibell You might want to pull my `matlab` now to make sure nothing got broken due to the latest changes to the memory management. I think the current design is nice and clean, and multiple modules now work... but... it's hard to make an omelette without breaking some eggs...

**Comment by ibell** [comment]
Yeah I can fire a build on our side to make sure that our examples still
run.

**Comment by KrisThielemans** [comment]
this seems to work, aside from issues with operator==(). I now have failures when comparing objects. any ideas?

**Comment by jaeandersson** [comment]
> this seems to work, aside from issues with operator==(). I now have failures when comparing objects. any ideas?

New issues with operator==? In matlabopers.swg, `operator==()` is renamed to `eq`. Does this not work?

**Comment by jaeandersson** [comment]
Have a look at 9ef94d49431de5bdaea1459a3fdb4d3c4dd693cb:

```
-%rename(isequal)        *::operator==;
+%rename(eq)             *::operator==;
```

That probably explains it.

**Comment by KrisThielemans** [comment]
correct. using eq works. Arguably, eq is the more natural choice syntax-wise.However, MATLAB says on the difference:

"When comparing handle objects, use eq or the == operator to test whether
objects are the same handle. Use isequal to test if objects have equal
property values, even if those objects are different handles."

(from http://uk.mathworks.com/help/matlab/ref/isequal.html)

So that could be interpreted as  eq should have failed (I'm comparing 2 different objects) while isequal should work. That would confuse people like crazy though. sigh.

**Comment by jaeandersson** [comment]
I don't know if @dcb210 had something in mind when he wrote that. The help for isequal suggests that isequal was already correct.

Another difference is the return value. `isequal` returns a scalar (1-by-1 matrix):

```
>> a = ones(3)

a =

     1     1     1
     1     1     1
     1     1     1

>> a==1

ans =

     1     1     1
     1     1     1
     1     1     1

>> isequal(a,1)

ans =

     0
```

In CasADi, we overload both eq and isequal the same way:

```
>> import casadi.*
>> x = DMatrix.eye(3)
x =

DMatrix(
[[1, 00, 00],
 [00, 1, 00],
 [00, 00, 1]])
>> x==0

ans =

DMatrix(
[[0, 1, 1],
 [1, 0, 1],
 [1, 1, 0]])
>> isequal(x,0)

ans =

     0
```

I see no reason to keep the default `compare handles` behaviour.

**Comment by KrisThielemans** [comment]
I would also prefer that eq and isequal behave the same. Not sure how we do that in general though (we cannot have 2 renames of course). we could add a isequal to SwgiRef that calls eq, but we're just trying to get rid of that one. maybe leave it to the user?

**Comment by jaeandersson** [comment]
As my example above shows, eq and isequal don't behave the same way to each other, nor should they IMO. So I defined them to work like you expect for MATLAB arrays (not MATLAB handles). But maybe that's that you meant.

I'd say that the natural is to have `operator==` be renamed `eq`. If the user wants to define an isequal method, he's free to do so.

**Comment by KrisThielemans** [comment]
sorry. I hadn't looked at this properly. yes, your Casadi strategy makes sense and would be as expected for MATLAB users. However, still not sure about the default. operator== returns a bool. isequal returns a bool. To me that means that those fit, and people can then add eq if they want.

choices!

set-able with %feature? (operator== to eq, isequal or both, as I don't look forward to adding eq (or isequal) to all my classes)

**Comment by jaeandersson** [comment]
There is nothing in C++ that requires you to have `operator==` return a bool. In CasADi, it will (for some classes) return a symbolic expression:

```
>> x = SX.sym('x');
>> y = SX.sym('y');
>> x==y

ans =

SX((x==y))
```

I don't see the problem of the current design honestly. To do `%rename` of operator== to `eq` by default makes sense since (among other reasons) `operator==` is not a valid name in MATLAB. But if it doesn't suite a project, you can rename it to something else in your ".i" file. Or you can rename something else to `eq`.

**Comment by dcb210** [comment]
Yes, that was my thought in making the change.

**Comment by jaeandersson** [comment]
I think what you really want is a kind of alias feature, to be able to define two different names for the same function. From what I can tell, Ruby has such a feature (called `%alias`). Then you can use that to make `isequal` an alias for `eq` and other similar things such as making `transpose` an alias for `ctranspose` (`A.'` vs `A'` in MATLAB which are the same if you don't have complex numbers). Or to make e.g. `x * y` behave like `x .* y`. That could be useful IMO, but I don't think it makes sense to have a feature specifically for `operator==`.

**Comment by KrisThielemans** [comment]
ok. I give in!

%alias would be useful but I think we have more urgent stuff to tackle.

**Comment by jaeandersson** [comment]
Created issue #57. Agree, other much more important things.

**Comment by KrisThielemans** [comment]
ok. now I have a really stupid question.

I now put 

> %rename(isequal) *::operator==;

in my .i, but it is ignored. Presumably because it's already renamed to eq. But

> %rename(isequal) *::eq;

doesn't work either. what do I do?

**Comment by jaeandersson** [comment]
Did you try putting it just before the first place where it is needed? Maybe it got shadowed by the default.

**Comment by KrisThielemans** [comment]
well yes. it gets shadowed, but how to I override it? I'll ask the mailing list
