### ISSUE TITLE
Broken access to internal attributes by returning references 

### ISSUE THREAD

**Issue by traversaro** [jaeandersson/swig#28]
After updating to the latest commit, I just noticed that accessing internal members by refence is now broken (I guess this was caused by the memory refactor in https://github.com/jaeandersson/swig/commit/04ab70695a7b353c7cd28f37221bae16576b6e67 ) .

I plan to better understand the issue and try to solve it in July, but in this issue I can already describe what stopped working. 

Basically, let's say that I have two classes `A` and `B`:

```
class B
{
private:  
     double value;
public:
     B()
     {
          value = 0.0;
     }
     void setValue(const double &_value)
     {
           value = _value;
     }
     double getValue() const
     {
          return value;
     }
}

class A 
{
private:
    B privateB; 
public:
    B& getB();
}
```

With the old behavior (and with other swig bindings, such as Lua and Python) I was able to do:

```
a = swig.A();
% the following command returns 0.0
a.getB().getValue()
% then we can set the value
a.getB().setValue(1.0)
% now the following line returns 1.0
a.getB().getValue()
```

The current behavior is instead:

```
a = swig.A();
% the following line returns 0.0
a.getB().getValue()
% then we can set the value
a.getB().setValue(1.0)
% the following line still returns 0.0 !
a.getB().getValue()
```

It is also possible that this is not actually a bug, but this is the indented behavior because in Matlab the "copy by value" is the default behavior.

**Comment by jaeandersson** [comment]
Hmm, I see. I guess the old behaviour is what you would expect since it explicitly returns a `B&` and not a `B` or `const B&`. If you can help debugging this, it would be great.

**Comment by traversaro** [comment]
Sure! We just have a deadline next week, so for the time being we will use the old version. Next week I will check how to solve the issue.

**Comment by jaeandersson** [comment]
I would have a look at this after doing another iteration on the core, in particular properly implementing #10 and #31.

**Comment by traversaro** [comment]
Ok, halting any investigation on the issue until then.

**Comment by jaeandersson** [comment]
On second thought, I'm not so sure this is related to #10 or #31. So please don't wait for this.

**Comment by traversaro** [comment]
I tried to start to debug this issue, and I noticed that I was wrong (or something else has changed in the master branch in the meanwhile). Apparently the references are correctly returned and can be manipulates as references, but some other memory issue is causing a lot of crashes. 

I pushed a brief example here : https://github.com/traversaro/swig-matlab-regression .
Basically, if I try do run the code in `runme.m` script, everything is working fine while I run this code:

``` matlab
% file: runme.m

% Create parent object
a = refToInternalObject.A();

% Get reference to the internal object
b1 = a.getB();
b2 = a.getB();

% b1 and b2 are references to the same object
disp(sprintf('b1: %f', b1.getValue()))
disp(sprintf('b2: %f', b2.getValue()))

disp('Setting b1 to 100')
b1.setValue(100)

disp(sprintf('b1: %f', b1.getValue()))
disp(sprintf('b2: %f', b2.getValue()))
```

The behaviour is the one expected, i.e. the script prints : 

```
b1: 0
b2: 0
b1: 100
b2: 100
```

However, if I try to execute the following lines:

```
disp(sprintf('a.b: %f', a.getB().getValue()))

disp(sprintf('b1: %f', b1.getValue()))
disp(sprintf('b2: %f', b2.getValue()))
disp(sprintf('a.b: %f', a.getB().getValue()))
```

The behaviour is not repetable anymore, and most of the time the script execution crashes with memory-related errors such as:

```
*** Error in `/usr/local/MATLAB/R2014a/bin/glnxa64/MATLAB': double free or corruption (out): 0x00007f70e64cb2a0 ***
```

```
*** Error in `/usr/local/MATLAB/R2014a/bin/glnxa64/MATLAB': free(): invalid pointer: 0x00007f402a1b5ff0 ***
```

```
*** Error in `/usr/local/MATLAB/R2014a/bin/glnxa64/MATLAB': corrupted double-linked list: 0x00007f7072532650 ***
```

Interestingly if the script is not failing on the first call to `a.getB().getValue()`, the script prints to screen:

```
b1: 0
b2: 0
b1: 100
b2: 100
a.b : 100
b1: rubbish numbers
b2: rubbish numbers
```

Apparently the call to a.getB() for some reason is corrupting the `privateB` or `value` members. 

The same scripts works perfectly with https://github.com/jaeandersson/swig/commit/e435cba21e33c664e8ee75f5f9bd17b245aeb0b7 .

**Comment by jaeandersson** [comment]
Hmm, ok. I hope to be able to get time to look at this before I go on vacation on Aug 1.

**Comment by traversaro** [comment]
I checked against the latest version of the repo and apparently the issue was solved. I don't know what commit solved the issue, but apparently the fix is related connected to `SWIG_Matlab_isOwned`. I will close for now,  and reopen if the issue emerges again.
