### ISSUE TITLE
check & warn for invalid %rename matlab function names

### ISSUE THREAD

**Issue by tesch1** [jaeandersson/swig#3]
for example this rename produces invalid matlab code:
%rename(**assign**) spin_system::operator=;

where matlab says:
Error using gammam.sys_dynamic
Error: File: sys_dynamic.m Line: 17 Column: 26
The input character is not valid in MATLAB statements or expressions.

and line 17 is:
    function varargout = **assign**(self,varargin)

this stackoverflow answer claims an expression ([A-Za-z][A-Za-z0-9_]*) for valid function names:
http://stackoverflow.com/questions/687605/in-matlab-what-ascii-characters-are-allowed-to-be-in-a-function-name

**Comment by jaeandersson** [comment]
I'm not sure I understand. How is "assign" not a valid function name?

**Comment by jaeandersson** [comment]
By the way @tesch1, feel free to fork the repo and make pull requests if you fix something.

**Comment by tesch1** [comment]
doh, I screwed up my copy paste, and pasted from a working version.

matlab function names can't start with '_'

I was using a .i file that was originally for python, so was renaming operator= to **assign**, but any function name starting with _ will choke matlab.

i've already forked, just not far enough along to understand how to fix anything yet :o)

**Comment by tesch1** [comment]
bwah, it's the github markup that's eating my underbars

**Comment by jaeandersson** [comment]
Oh, ok. So if I understand correctly it's a problem with your .i file and not with the MATLAB module. I think you need to add something like:

``` c++
#ifdef SWIGMATLAB
%rename(somethingwithoutunderscore) spin_system::operator=;
#endif
```

Or do you think that the MATLAB module should resolve this automatically?

FYI: I'm starting to work the MATLAB module again now.

**Comment by tesch1** [comment]
I think that swig's matlab interface should check for invalid matlab function names, because it shouldn't ever produce invalid matlab code (which it is currently doing without even a warning).  That said, I've spent a little more time with it, and I think I can probably come up with a fix, or at least produce a warning message when trying to swig function names that are valid in c/c++ but not in matlab (just a quick check to make sure function names dont start with _).

**Comment by jaeandersson** [comment]
Ah, I see. Yes, a warning or error message should definitely be emitted.

**Comment by tesch1** [comment]
this: https://github.com/tesch1/swig/commit/314daed0b094a98ba94841afe6b9f977b508f4c0 produces a warning message when generating invalid symbol names
