### ISSUE TITLE
Consider using module name instead of intermediate c++ file name as mex_file name

### ISSUE THREAD

**Issue by rdeits** [jaeandersson/swig#44]
Currently, swig-matlab uses the name of the generated cxx file as the mex function name. I assume that's because it's conventional in Matlab for the mexfile to match the name of its cxx source file (since that's what the `mex` command does by default). That's reasonable, but I'd suggest considering using the actual module name instead. 

The build process provided by Cmake, contained in UseSWIG.cmake, results in a generated cxx file with a language-specific filename, something like:

```
mymodulePYTHON_wrap.cxx
```

but the final generated library is named to nicely match the SWIG module name:

```
_mymodule.so
mymodule.py
```

UseSWIG.cmake produces similar results for Matlab, with an intermediate file name `mymoduleMATLAB_wrap.cxx` and a compiled mex file named `mymodule.mexmaci64` or similar. But because swig-matlab internally assumes that the mex file will be named `mymoduleMATLAB_wrap` to match the .cxx file, the resulting bindings can't be used without some renaming. 

Of course, there are lots of other ways to build swig bindings without that particular cmake library, but since it's installed with cmake its likely to be used by others in the future. Fixing this is just a matter of setting `mex_fcn = pkg_name;` in `matlab.cxx`. 

Was it intentional to make the mex function match the .cxx file instead of the module name? Or is this something you'd be interested in changing?

**Comment by jaeandersson** [comment]
> Was it intentional to make the mex function match the .cxx file instead of the module name? Or is this something you'd be interested in changing?

I don't think it was intentional. I guess the MATLAB-unique suffix will prevent name conflicts with other SWIG modules (for us who generate interfaces to multiple languages). Feel free to make a pull request.

**Comment by jaeandersson** [comment]
I don't quite understand this issue. From my understanding, multiple modules can share the same `pkg_name`, so I don't see how you can have `mex_fcn = pkg_name`. We use CMake (and UseSWIG.cmake) to build our SWIG-MATLAB modules and it works. Iirc, we did some changes to it though. If the problem is a limitation in `UseSWIG.cmake`, we should fix it and make a pull request to cmake.

**Comment by jaeandersson** [comment]
I've changed the naming of the c/c++ wrapper file to `{module_name}{mex_infix}.{mex_suffix}`, where `{mex_infix}` is `_wrap` by default. E.g. for a module `foo` on a Mac, you get the filename `foo_wrap.mexmaci64`. Note that this is independent of how the c/c++ wrapper is named. You can change this by setting the new "-mexinfix" option. E.g., to get the old behaviour with UseSWIG.cmake, set suffix to "MATLAB_wrap":

```
set(SWIG_MODULE_casadiMATLAB_wrap_EXTRA_FLAGS "-mexinfix" "MATLAB_wrap")
```

Ping @KrisThielemans @rdeits @jgillis @dcb210 @traversaro @tesch1: Careful when pulling, you might need to update your build system.

**Comment by rdeits** [comment]
Okay, sounds good to me. Thanks!
