### ISSUE TITLE
Windows spaces in MATLAB path makes test-suite and examples fail

### ISSUE THREAD

**Issue by KrisThielemans** [jaeandersson/swig#46]
On Windows, MATLAB usually sits in C:\Program Files. This creates problems in the test-suite. I've fixed this by inserting some spaces. It also works on Linux as far as my tests goes. The commit is here

https://github.com/KrisThielemans/swig/commit/f0b4c49f798b619bf30e4bcd36d81de45c44a38f

**Comment by jaeandersson** [comment]
I've pulled your branch.
