### ISSUE TITLE
Refactor error handling

### ISSUE THREAD

**Issue by jaeandersson** [jaeandersson/swig#58]
Right now errors messages in the wrappers raise warnings instead of errors in MATLAB followed by a generic error message at the end. It should be possible to avoid these warning messages by instead constructing an MException array with all the error information and return this to the mexFunction gateway.

This means function signature of the structure of the wrapper functions from:

``` c
int _wrap_foo(int resc, mxArray *resv[], int argc, mxArray *argv[]) {
 ...
}
```

to

``` c
mxArray* _wrap_foo(int resc, mxArray *resv[], int argc, mxArray *argv[]) {
 ...
}
```

On success, it would return 0 (cf. mexCallMATLABWithTrap).

**Comment by jaeandersson** [comment]
@jgillis - I think it could this could avoid the use of matlabprepend/matlabappend.

**Comment by KrisThielemans** [comment]
how's this related to Issue #48

**Comment by jaeandersson** [comment]
#48 is indeed essentially a duplicate of this, I'll close that one. See also my comment there though.

**Comment by jaeandersson** [comment]
Resolved.
