### ISSUE TITLE
Redirect std::cout and std::cerr

### ISSUE THREAD

**Issue by jaeandersson** [jaeandersson/swig#7]
It makes sense to redirect std::cout to a stream that prints to mexPrintf. Such a stream can be implemented as follows:

``` c++
#include <streambuf>
#include <ostream>
  namespace swig {
    /** Stream buffer to allow printing to mex conveniently
        Adapted from answer to stackoverflow question 243696.
    */
    class mex_buf : public std::streambuf {
    public:
      mex_buf() {}
    protected:
      virtual int_type overflow(int_type ch) {
        if(ch != traits_type::eof()) {
          mexPrintf("%c", static_cast<char>(ch));
        }
        return ch;
      }
      /* virtual int sync() { // needed?
         mexEvalString("drawnow;");
         return 0;
      } */
      virtual std::streamsize xsputn(const char* s, std::streamsize num) {
        mexPrintf("%.*s", static_cast<int>(num), s);
        return num;
      }
    };

    // Corresponding output stream
    class mexostream : public std::ostream {
    protected:
      mex_buf buf;
    public:
      mexostream() : std::ostream(&buf) {}
    };
  } // namespace swig
```

The redirection can be done in the mexFunction function:

``` c++
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]){
   ...
   swig::mexostream mex_cout;
   std::streambuf *cout_backup = std::cout.rdbuf(&mex_cout);
   ...
    std::cout.rdbuf(cout_backup); // restore
   ..
}
```

In a similar way, std::cerr can be made to print MATLAB warning messages (don't think you want to print errors since that will interrupt the execution).

**Comment by jaeandersson** [comment]
@KrisThielemans @ibell - Is this is a good idea?

**Comment by ibell** [comment]
What's the logic here?  You want to grab the cout and cerr streams and redirect them to matlab?  I thought this already worked...  Doesn't std::cout output already end up in the matlab console?

**Comment by tesch1** [comment]
It just so happens that I ran into this today... it seems only newer matlab versions do this, at least it does not grab cout on OSX + 2011b... (but does grab it on Linux 2012b -- those being the only two versions I have access to)  Maybe it should be a configurable option?

**Comment by KrisThielemans** [comment]
it's indeed OS dependent. on Windows, you don't see what's written to stdout and stderr. you have to use mexPrintf if you want the matlab console to see it.

i'm not sure if this is required or a good idea, or indeed even possible. If you do it, I presume you would have to grab stdout and stderr somehow. I'd then use a configurable option indeed.

low priority in my opinion.

**Comment by jaeandersson** [comment]
On OS X and Matlab 2014b, std::cout can be seen if you run "-nodesktop", but not if you start the GUI.

**Comment by KrisThielemans** [comment]
Sure. That will always be the case.

**Comment by jaeandersson** [comment]
This is a big annoyance for me, so I'll give this a shot. I think the natural behaviour would be to have std::cout be redirected to mexPrintf and std::cerr be redirected to mexWarnMsgIdAndTxt. I don't see why this shouldn't be the default behaviour in MATLAB as default behaviour doesn't make much sense.

**Comment by KrisThielemans** [comment]
hi

the more I think about this, the harder it looks. I can't see any way to intercept e.g. std::cout in a library to which you have no access to. you can redirect stdout with freopen (see e.g. http://stackoverflow.com/questions/28341419/redirect-c-library-stdout-messages-in-python)

it is somewhat questionable if this can be done reliably for MATLAB. somebody could be running with -nodesktop which presumably will make mexPrintf write to stdout, leading to a nice infinite loop.

**Comment by jaeandersson** [comment]
@KrisThielemans Look at the implementation I just pushed. I think this is pretty safe. Reopen if problem lingers.
Note that this doesn't capture output written using `printf` or `fprintf`. I'm struggling to find a way to capture such output.
Reopen if needed.

**Comment by jaeandersson** [comment]
OK, so I'm going to reopen this myself. While this works fine, I realise why this shouldn't be the default behaviour. Redirecting std::cout and std::cerr can be a bit sensitive. So I'll add a feature for enabling this.
