### ISSUE TITLE
Windows binaries for swig-matlab 

### ISSUE THREAD

**Issue by giumas** [jaeandersson/swig#72]
Are there plans to provide beta `swig-matlab` binaries for Windows?

**Comment by jaeandersson** [comment]
I guess that will happen as soon as the branch is merged with SWIG master.

**Comment by giumas** [comment]
> I guess that will happen as soon as the branch is merged with SWIG master.

These would be great news.. do you have updates on that side?

**Comment by jaeandersson** [comment]
I hope that it will happen in the next couple of weeks/months. At the moment I'm waiting for feedback.

**Comment by giumas** [comment]
> I hope that it will happen in the next couple of weeks/months.

Pretty cool!

**Comment by jaeandersson** [comment]
Don't take that as a promise though. It's all subject to approval from SWIG devs.

**Comment by hmaarrfk** [comment]
Any update on this? It would be nice to have binaries for easy windows installation.

**Comment by hmaarrfk** [comment]
I went through the exercise in case anybody is feeling a little lazy. Let me know if this works.
[swigwin-matlab-8b286bb.zip](https://github.com/jaeandersson/swig/files/1550135/swigwin-matlab-8b286bb.zip)

Edit: removed the space from the foldername

**Comment by jaeandersson** [comment]
No update. I haven't been able to spend a lot of time on this lately.
