### ISSUE TITLE
Some question about how to run

### ISSUE THREAD

**Issue by hengjiUSTC** [jaeandersson/swig#90]
Hi I am quiet new to this and I try to run example/matlab/simple.  
first i run swig -matlab example.i 
and at matlab I run \: mex example.c example_wrap.cxx
but I still can't run runme.m 
Can you give me some advice on how to use it?

**Comment by hengjikolmostar** [comment]
I have successfully run it but comes another question. I defi

**Comment by kdheepak** [comment]
Were you able to figure this out? Can you share how you went about doing this?

**Comment by kdheepak** [comment]
@jaeandersson any advice on how to run this. There's no documentation as far as I can tell. I'm able to do the following.

```matlab
>> mex example_wrap.cxx example.c
Building with 'Xcode Clang++'.
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]

MEX completed successfully.
```

However, I'm not able to run `runme.m`, since there is no `swigexampleMEX` function.

**Comment by kdheepak** [comment]
Okay it looks like SWIG is not generating the right names (?). On renaming the function name, this example seems to work.
